---
title: "Lab3-template-exercises"
author: "Claire Donnat"
date: "6/22/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exercise 1: R Basics 

**Material: Week 1 Session 2**

## a. Arithmetic operations

Compute the following using R:

* $4.84 \log_{10}(51!)$, where $x!$ is factorial of $x$
* $4.02 \sqrt[3]{7^2 + e^7}$
* $20\cos( 2\pi + 0.25) + 32 \sin \left({3 \pi \over 4} \right)$
* $\left \lfloor {4.011 \pi \over 3}  {5 \choose 2} \right \rfloor$, where
$\lfloor x \rfloor$ means rounding to the largest integer not greater than x.
where ${x \choose y}$ is the notation for [combination](https://en.wikipedia.org/wiki/Combination)
* $8.1 \sum_{i = 1}^{100} {1 \over i}$


## b. Matrix operation

Generate a matrix $A$ with 15 rows and 5 columns with entries 
being random uniform numbers on an interval $[0, 1]$.
Then generate a matrix $B$ with 5 rows and 7 columns where entries
drawn from a Gaussian distribution with mean 0 and variance 10.
Use `set.seed()` function with a chosen seed (record the seed)
for reproducibility. Type in `?set.seed` in the R console to learn
more about the function. With the two matrices compute:

* $AB$ (a matrix product)
* multiply the 3rd row of $A$ by the 4th column of $B$ and compute
the sum of entries in the resulting vector, then check that agrees with
a corresponding term in the matrix product you computed in the previous
part.
* obtain a vector which is a product of matrix multiplication
between in matrix $A$ and the 4th column of $B$. 


## c. Factors 

In this part of the exercise we use a built-in data set, `sleep`, 
on student's sleep. This data stores information on the 
increase in hours of sleep, type of drug administered, and the patient ID,
in respective columns. You can learn more about this dataset from the page,
accessed by calling `?sleep`. 

The column `ID` for patient identity is a factor with labels from 1 to 10.
Rename the ID labels to letters of the alphabet in the reverse order,
with label "A" assigned to patient 10, "B" to patient 9, "C" to patient 8, 
..., and "J" to patient 1.


## d. Data Frame

Create a data frame, 'birthdays', which stores information on 
the birthdays of 5 people either real of fictional. 
The data table should have columns:

1. 'first': first name
2. 'last': last name
3. 'birthday': the person's birthday in format YYYY-MM-DD ("%Y-%m-%d")
4. 'city': city where the person lives

Convert the birthdays to date objects using `as.Date()` function.
Compute the difference (in days) between your birthday and the birthday 
of each of the people and append that information as a new column 
'bday_diff' of the data-frame.


# Exercise 2: Programming 


## a. Parametric function 

* Write a function in are that evaluates the following:

\begin{align*}
f(\theta) &= 7 - 0.5\sin(\theta) + 2.5\sin(3\theta) + 2\sin(5\theta) - 1.7\sin(7\theta) + \\
& \quad  +  3\cos(2\theta) - 2\cos(4\theta) - 0.4\cos(16\theta)
\end{align*}

* Generate a vector, \texttt{theta}, equal to a sequence from $0$ to $2\pi$ 
with increments of $0.01$
* Compute a vector $x = f(\theta) \cdot \cos(\theta)$ and 
$y = f(\theta) \cdot \sin(\theta)$ for $\theta$ you just created.



## b. Multiple arguments 

Write a function `time_diff()` that takes two dates as inputs and returns
the difference between them in units of "hours", "days", "weeks", "months",
or "years", defined by an optional argument 'units', set by default
to "days". Use the function to compute time left to your next birthday
separately in units of: months, days, and hours.
 

## c. Control flow: Fibonacci numbers

Fibonacci sequence starts with numbers 1 and 2, and each subsequent term 
is generated by adding the previous two terms. The first 10 terms of 
the Fibonacci sequence are thus: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... .
Find the total sum of **even numbers** in the Fibonacci sequence, 
each not exceeding one million.

# Exercise 3: Data Import/Export and transformation [20pt]

**Material: Week 1 Session 3.**

## a. Import data

Visit the following URL:
https://raw.githubusercontent.com/biox-rbootcamp/biox-rbootcamp.github.io/master/assets/data/share-of-people-who-say-they-are-happy.txt

Observe the structure and format of the data. Then, use a function from
`readr` package to read the data in the URL into R.
Then, find the country with the highest share of happy people in 2014.

## b. Export data 

Filter observations from the data set on happiness that correspond to years 
after 2000. Export the subset of the data as a tab-delimited text file 
to a chosen location on your computer.
