---
title: "Cluster_Ex"
author: "Laura Symul"
date: "6/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("ggplot2")
library("dbscan")
```



## K-means vs K-medoids


```{r data, fig.width=6, fig.height=2}

Xm = rbind(
  c(1,2),
  c(2,1),
  c(1.5,2.5),
  c(1.5,1.5),
  c(2,2),
  c(15,2)
)

X_means = data.frame(x = Xm[,1], y = Xm[,2], type = "observations", method = "k-means")
X_medoids = data.frame(x = Xm[,1], y = Xm[,2], type = "observations", method = "k-medoids")
X = rbind(X_means, X_medoids)

x_means = apply(Xm, 2, mean)
x_means = data.frame(x = x_means[1], y = x_means[2], type = "center", method = "k-means")

dist_medoids = as.matrix(dist(Xm))
dist_medoids = apply(dist_medoids, 1, sum)
x_medoids = Xm[which.min(dist_medoids),]
x_medoids = data.frame(x = x_medoids[1], y = x_medoids[2], type = "center", method = "k-medoids")


X = rbind(X_means, x_means, X_medoids, x_medoids)

X$method = factor(X$method, levels = c("k-medoids","k-means"))


ggplot(X, aes(x = x, y = y, col = type, shape = type))+ 
  geom_point()+
  facet_grid( . ~ method)+
  scale_shape_manual(values = c(16,3))+
  scale_color_manual(values = c("deeppink","black"))+
  xlab("")+ylab("")+
  guides(col = FALSE, shape = FALSE, size = FALSE)+
  theme_light()




```


# K-means


```{r fig.height=5, fig.width=5}
set.seed(952224887)

Xmat=matrix(runif(200),ncol=2)
nk=3
cents=matrix(runif(2*nk),ncol=2)

out=kmeans(Xmat,centers = nk) # give the # of clusters
out=kmeans(Xmat,centers = cents) # give the seeds (initial center of clusters)

X = data.frame(x = Xmat[,1], y = Xmat[,2], cluster = factor(out$cluster))
cents_df = data.frame(x = cents[,1], y = cents[,2], num = factor(1:3))
cents_out = data.frame(x = out$centers[,1], y = out$centers[,2], num = factor(1:3))

out1=kmeans(Xmat,cents,iter.max=1) # does not converge in 1 iteration
out2=kmeans(Xmat,cents,iter.max=2) # converges in 2 iteration (check out2 or out1$iter)
out3=kmeans(Xmat,cents,iter.max=3) # out3$iter = 2

X$cluster1 = factor(out1$cluster)
X$cluster2 = factor(out2$cluster)
X$cluster3 = factor(out3$cluster)

cents_out1 = data.frame(x = out1$centers[,1], y = out1$centers[,2], num = factor(1:3))
cents_out2 = data.frame(x = out2$centers[,1], y = out2$centers[,2], num = factor(1:3))
cents_out3 = data.frame(x = out3$centers[,1], y = out3$centers[,2], num = factor(1:3))

g = ggplot(X, aes(x = x, y = y)) + xlab("") + ylab("") + guides(col = FALSE)
g + geom_point() + geom_point(data = cents_df, aes(x = x, y = y, col = num), shape = "+", size = 10)
g + geom_point(aes(col = cluster)) + geom_point(data = cents_out, aes(x = x, y = y, col = num), shape = "+", size = 10)
g + geom_point(aes(col = cluster1))+ geom_point(data = cents_out1, aes(x = x, y = y, col = num), shape = "+", size = 10)
g + geom_point(aes(col = cluster2))+ geom_point(data = cents_out2, aes(x = x, y = y, col = num), shape = "+", size = 10)
g + geom_point(aes(col = cluster3))+ geom_point(data = cents_out3, aes(x = x, y = y, col = num), shape = "+", size = 10)

```


# Hierarchical clustering


```{r}
set.seed(1)
Xmat=matrix(runif(20),ncol=2)
d = dist(Xmat)
d
dmat = as.matrix(d)
dmat[upper.tri(dmat, diag = TRUE)] = Inf
o = order(dmat, decreasing = FALSE)


X = data.frame(x = Xmat[,1], y = Xmat[,2], n = 1:nrow(Xmat))

g = ggplot(X, aes(x = x, y = y)) + coord_fixed()+ geom_point() + geom_text(aes(label = n), hjust=0, vjust=-0.65) + xlab("") + ylab("") + theme_light() # theme_few()
g 

df_lines = data.frame()
for(k in 1:10){
  cat(k,"\n")
  a = (o[k]-1) %% ncol(dmat)+1
  b = (o[k]-1) %/% ncol(dmat) + 1
  xA = X$x[a]; yA = X$y[a]
  xB = X$x[b]; yB = X$y[b]
  df_lines = rbind(df_lines, data.frame(xA = X$x[a], yA = X$y[a], xB = X$x[b], yB = X$y[b]))
  g = g + geom_segment(data = df_lines, aes(x = xA, y = yA, xend = xB, yend = yB), col = "red")
  print(g)
}



```


```{r fig.width=3, fig.height=3}


clust = hclust(d, method = "ward.D")
plot(clust)

clust = hclust(d, method = "complete")
plot(clust)

```


# Comparison k-means, hierarchical, dbscan

```{r}

set.seed(4)

Xmat_1 = matrix(rnorm(400, 0.25, 0.1), ncol = 2)
Xmat_2 = matrix(rnorm(400, 0.75, 0.2), ncol = 2)
Xmat_3 = matrix(runif(400),ncol=2)
Xmat=rbind(Xmat_1, Xmat_2, Xmat_3)


# k-means
out_kmeans = kmeans(Xmat, centers = 2)


# hierarchical
d = dist(Xmat)
h = hclust(d, method = "ward.D")

c = cutree(h, k = 2)

# dbscan
kNNdistplot(Xmat, k = 3) #k = dim+1 # we look for the knee
abline(h=.06, col = "red", lty=2) # the knee is ~ for dist = 0.08


out_dbscan = dbscan(Xmat, eps = 0.06, minPts = 5) # eps = 0.05
out_dbscan
# hullplot(Xmat, out_dbscan)

X = data.frame(x = Xmat[,1], y = Xmat[,2],
               true = factor(c(rep(1,200),rep(2, 200),rep(3, 200))),
               kmeans = factor(out_kmeans$cluster),
               hierarchical = factor(c),
               dbscan = factor(out_dbscan$cluster)
)



g = ggplot(X, aes(x = x, y = y)) + coord_fixed() + xlab("") + ylab("")
g + geom_point() + ggtitle("dataset")

g + geom_point(aes(col = kmeans)) + ggtitle("k-means")

g + geom_point(aes(col = hierarchical)) + ggtitle("hierarchical")
plot(h)

g + geom_point(aes(col = dbscan)) + ggtitle("dbscan")

g + geom_point(aes(col = true)) + ggtitle("'true' labels")

```








